version: '3'
services:
  # Nginx server configuration
  web:
    image: nginx:1.18.0
    container_name: webserver-react
    depends_on:
      - php
    links:
      - php
    volumes:
      - ./:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d/
    ports:
      - "8080:80"
  # Php-fpm configuration
  php:
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
